name: Data Node 001 Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/Storage/**'
      - 'infra/KeyVault/**'
      - 'infra/PrivateEndpoint/**'
      - '.github/workflows/dataNode001Deployment.yml'

env:
  AZURE_RESOURCE_GROUP: datanode001-storage
  AZURE_LOCATION: northeurope

jobs:
  deployment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create resource group
    - name: Create resource group
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group ${{ env.AZURE_RESOURCE_GROUP }}"
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP }}
    
    # # Deploy key vault
    # - name: Deploy key vault
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       echo "Creating deployment in resource group"
    #       az deployment group create \
    #         --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
    #         --template-file $GITHUB_WORKSPACE/infra/KeyVault/deploy.keyVault.json \
    #         --parameters $GITHUB_WORKSPACE/infra/KeyVault/params.keyVault001.json
    
    # Deploy storage account - dev
    - name: Deploy storage account - dev
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Deploy storage account - test
    - name: Deploy storage account - test
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Deploy storage account - prod
    - name: Deploy storage account - prod
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Deploy storage account - prod
    - name: Deploy storage account - prod
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
